version: '2'
services:

  # "app" would be your application server ...
  # could be configured as a backend of nginx ...
  # similar to how nginx is configured as a backend of varnish ...
  # here it is a simple node app 
  backendb:
    build:
      context: .
      dockerfile: ./backendb/Dockerfile
    ports:
      - "9000:9000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backendb
    links:
      - backendb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/backendb.conf:/etc/nginx/conf.d/backendb.conf
    restart: unless-stopped

  varnish:
    build:
      context: .
      dockerfile: ./varnish/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nginx
    links:
      - nginx
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    restart: unless-stopped
